CSE 291 Progress Report
yiying-zhang/Serverless-LegoOS pull request #5
Opened 2020-02-18 07:31 UTC by yuxuan3713

This PR includes changes made on yuxuan-dev for project progress. Base on the our workflow, this PR may seem to contain a lot of debugging commits. This PR is **not** for merge to master branch, but servers as a checkpoint.

**Recap on ourworkflow:**
- yuxuan-dev includes newest code change
- yuxuan-dev-memory and yuxuan-dev-processor are both 1 commits ahead of yuxuan-dev, and are configured for mComponent and pComponent respectively.
- After code change made to yuxuan-dev, yuxuan-dev-memory and yuxuan-dev-processor are rebased. All of three branches are pushed to GitHub and pulled to Cloudlab VM, compiled and tested.

**Progress made for sys call and p2m messaging:**

- Defined new syscall “state_dummy_get” (will be removed once APIs are functioning)
- Implemented dummy syscall number in syscall64.tbl
- Implemented dummy syscall in state.c, sending P2M msg upon syscall
- Defined P2M message opcode / msg struct / reply struct
- Implemented dummy message handler, echos input and replies
- Resolved dependency issues during implementation
- Ran dummy syscall + p2m messaging successfully
- The code structure for our project is mostly established and tested. We will fill in more APIs and functions as they are implemented and replace any dummies.

**Current dummies:**
- Dummy syscall definition
- Dummy syscall implementation, sending message to mComponent
- Dummy message handler, echos message
- Dummy test, piggy backed on general.c (piggy piggy back...)
- Tested successful syscall from pComponent, messaged mComponent, echoed message, and returned echo message to pComponent. (Details available in log files)

**Note:**
**This PR is not for merge to master branch** as it contains a lot of dummies and debugging codes. However, it reflects a working layout of our project progress and an established workflow. It will be meaningful to check for the working logic of this project. We will replace any dummies and fill in new implementations as the project goes on. We will create new "mergeable" PRs once they mature and fit in master branch.

2020-02-23 02:33 UTC, yiying-zhang requested changes
Think you'll need some changes once you start building the real handler and functionalities (which you should start doing asap to still meet you schedule).

2020-02-23 02:33 UTC, yiying-zhang commented on arch/x86/entry/syscalls/syscall_64.tbl
> +666 common  dummy_get       sys_dummy_get
user proper spacing (follow previous lines of tabs)

2020-02-23 02:33 UTC, yiying-zhang commented on kernel/sys.c
> +#include <processor/state.c>
why are you include .c file??

2020-02-23 02:33 UTC, yiying-zhang commented on managers/memory/core.c
> +//	State Management SYSCALL
follow the above sections format and use /* ..... */

2020-02-23 02:33 UTC, yiying-zhang commented on managers/memory/handle_state.c
> +//
We'll need to add proper header with copyright info when this is ready to be merged.

2020-02-23 02:33 UTC, yiying-zhang commented on managers/memory/handle_state.c
> +void handle_p2m_state_dummy_get(struct p2m_state_struct *payload, struct thpool_buffer *tb)
later on when you have real functions, before each function you should add a comment section like
```
/*
 * simple explanation of the function
 */
```

2020-02-23 02:33 UTC, yiying-zhang commented on managers/memory/core.c
> +	    handle_p2m_state_dummy_get(payload, buffer);
I think you should also pass hdr into this function, since the real handler would need info like src_nid

2020-02-27 04:55 UTC, Tian-Qiu commented on kernel/sys.c
> +#include <processor/state.c>
We got confused about function definitions in sys.c and now it seems that both pComp and mComp compile it (functions with BUG() are not accessible to any Comps) and even though mComp doesn't call any syscall, it has to know the definition in missing_syscall.c. This dependency is correctly handled in the next pr.

2020-02-27 04:56 UTC, Tian-Qiu commented on arch/x86/entry/syscalls/syscall_64.tbl
> +666 common  dummy_get       sys_dummy_get
Fixed.

2020-02-27 04:58 UTC, Tian-Qiu commented on managers/memory/core.c
> +//	State Management SYSCALL
Fixed.

2020-02-27 04:58 UTC, Tian-Qiu commented on managers/memory/handle_state.c
> +//
Fixed

2020-03-21 04:47 UTC, closed without merging